package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.PneumaticsModuleType;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
public class PneumaticsSubsystem extends SubsystemBase {
    
    private final Solenoid solenoid = new Solenoid(PneumaticsModuleType.CTREPCM, 5);
    private boolean isExtended = false;
    
    
    public PneumaticsSubsystem() { solenoid.set(true);}

    public void extendSolenoid() {
        isExtended = true;
        solenoid.set(isExtended);
    }

    public void releaseCoral() {
        isExtended = false;
        solenoid.set(isExtended);
    }

}

